spring.application.name=asesorias

# ===== Conexion a PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/asesorias_db
spring.datasource.username=postgres
spring.datasource.password=CAMBIA_POR_TU_PASSWORD_DE_POSTGRES
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
# 'none' = Hibernate NO crea ni modifica tablas. Nosotros manejamos schema.sql a mano.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== Servidor =====
server.port=8080